"""empty message

Revision ID: 3c5dd77f84dd
Revises: 
Create Date: 2024-03-19 15:36:56.826958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5dd77f84dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habitat_name', sa.String(length=120), nullable=False),
    sa.Column('habitat_description', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habitat_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_name', sa.String(length=120), nullable=False),
    sa.Column('char_description', sa.String(length=240), nullable=False),
    sa.Column('char_img_url', sa.String(length=240), nullable=True),
    sa.Column('char_habitat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['char_habitat'], ['habitat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('char_name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fav_user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('fav_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('habitat')
    # ### end Alembic commands ###
