"""empty message

Revision ID: 4146aa58be2d
Revises: 1e75a053ab46
Create Date: 2024-03-18 20:24:34.332849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4146aa58be2d'
down_revision = '1e75a053ab46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fav_user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['fav_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
